src/app.py
from flask import Flask, render_template
from src.common.database import Database

app = Flask(__name__)
app.config.from_object('config')
app.secret_key="123"

@app.before_first_request
def init_db():
    Database.initialise()

@app.route('/')
def home():
    return render_template('home.jinja2')

from src.models.users.views import user_blueprint
from src.models.alerts.views import alert_blueprint
from src.models.stores.views import store_blueprint
app.register_blueprint(user_blueprint,url_prefix="/users")
app.register_blueprint(alert_blueprint,url_prefix="/alerts")
app.register_blueprint(store_blueprint,url_prefix="/stores")

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session

from src.models.alerts.alert import Alert
from src.models.items.item import Item

alert_blueprint = Blueprint('alerts',__name__)

@alert_blueprint.route('/')
def index():
    return "This is the alerts index"

@alert_blueprint.route('/new',methods=['GET','POST'])
def create_alert():
    if request.method == 'POST':
        name=request.form['name']
        url = request.form['url']
        price_limit = request.form['price_limit']

        item = Item(name,url)
        item.save_to_mongo()

        alert= Alert(session['email'],price_limit,item._id)
        alert.load_item_price()

    return render_template('alerts/new_alert.jinja2')

@alert_blueprint.route('/deactivate/<string:alert_id>')
def deactivate_alert(alert_id):
    pass

@alert_blueprint.route('/<string:alert_id>')
def get_alert_page(alert_id):
    alert= Alert.find_by_id(alert_id)
    return render_template('alerts/alert.jinja2',alert=alert)

@alert_blueprint.route('/for_user/user_id')
def get_alerts_for_user(user_id):
    pass

src/models/items/views.py
from flask import Blueprint

item_blueprint = Blueprint('items',__name__)

@item_blueprint.route('/item/<string:name>')
def item_page(name):
    pass

src/models/stores/views.py
from flask import Blueprint

store_blueprint = Blueprint('stores',__name__)

@store_blueprint.route('/')
def index():
    return "This is the stores index"

@store_blueprint.route('/store/<string:name>')
def store_page():
    pass

src/models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template
from src.models.users.user import User
import src.models.users.errors as UserErrors

user_blueprint =Blueprint('users',__name__)

@user_blueprint.route('/login',methods =['GET','POST'])
def login_user():
    if request.method =='POST':
        email= request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email,password):
                session['email']=email
            return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
           return e.message
    return render_template("users/login.jinja2")



@user_blueprint.route('/register',methods=['GET','POST'])
def register_user():
    if request.method =='POST':
        email= request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2")

@user_blueprint.route('/alerts')
def user_alerts():
    user= User.find_by_email(session['email'])
    u_alerts=user.get_alerts()
    return render_template('users/alerts.jinja2',alerts= u_alerts)

@user_blueprint.route('/logout')
def logout_user():
    session['email']=None
    return redirect(url_for('home'))

@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <p> {{ alert.item.name }} </p>
{% endblock %}

src/templates/alerts/create_alert.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/alerts/edit_alert.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/alerts/new_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
          <h1>Create Alert</h1>
    </div>
    <div class="form-size">
          <form method="post">
              <div class="form-group">
                  <label for="name">Alert/Item/Name</label>
                  <input type="text" class="form-control" id="name" name="name" placeholder="Name">
              </div>
               <div class="form-group">
                  <label for="url">URL</label>
                  <input type="text" class="form-control" id="url" name="url" placeholder="http://">
              </div>
              <div class="form-group">
                  <label for="price_limit">Alert limit</label>
                  <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45" aria-describedby="priceLimitBlock">
                  <p id="priceLimitBlock" class="help-block">Email will be sent when the price reaches under this value</p>
                  <button type="submit" class="btn btn-default">Create</button>
              </div>
          </form>
    </div>

{% endblock %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing Alerts Service</title>

    {% include "html_dependencies.jinja2" %}

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        <div class="navbar-header">
            <a class="navbar-brand" href="/" title="Home">Pricing Alerts</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li> <a href={{ url_for('stores.index') }}>Stores</a> </li>
                <li> <a href={{ url_for('alerts.index') }}>Alerts</a> </li>
            </ul>
            {% if session['email'] %}
            <ul class="nav navbar-nav navbar-right">
                <li> <a href={{ url_for('users.user_alerts') }}> <span class="glyphicon glyphicon-alert"> </span> Your Alerts</a> </li>
                <li> <a href={{ url_for('users.logout_user') }}> <span class="glyphicon glyphicon-log-out"></span> Log Out</a> </li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
                <li> <a href={{ url_for('users.register_user') }}> <span class="glyphicon glyphicon-user"> </span> Sign Up</a> </li>
                <li> <a href={{ url_for('users.login_user') }}><span class="glyphicon glyphicon-log-in"></span> Login</a> </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>


<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}

{% block content %}
    <div class="jumbotron">
        <h1>Pricing Alerts System!</h1>
        <p>The app scans the e-commerce webstores to alert price drops of the items you are interested in</p>
        <p>Register and add the url of the item that you want to scan and we'll take of the rest</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign Up</a></p>
    </div>
{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

src/templates/store/create_store.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/store/edit_store.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/store/store.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Alerts
            <small>Showing already existing alerts</small>
        </h1>
    </div>
    <div class="list-group">
        {% for alert in alerts %}
            <a href={{ url_for('alerts.get_alert_page',alert_id =alert._id) }} class="list-group-item">
                <h4 class="list-group-item-heading">Alert for {{ alert.item.name }}</h4>
                <p class="list-group-item-text">Last price found <strong>{{ alert.item.price }}</strong><br/>
                Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H:%M") }}</strong></p>
            </a>
        {% endfor %}
    </div>
    <a class="btn btn-success" href="{{ url_for('alerts.create_alert') }}"><span class="glyphicon glyphicon-plus"></span> Create new</a>
{% endblock %}

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.login_user') }}" method="post" >
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-success">Log in</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.register_user') }}" method="post" >
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-success">Sign Up</button>
        </form>
    </div>
{% endblock %}